using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventHub.Migrations
{
    public partial class InitTelegramVerification : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_class c
                    JOIN pg_namespace n ON n.oid = c.relnamespace
                    WHERE c.relkind = 'r'
                    AND c.relname = 'TelegramVerifications'
                ) THEN
                    CREATE TABLE ""TelegramVerifications"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""UserId"" integer NOT NULL,
                    ""ChatId"" bigint NOT NULL,
                    ""Code"" integer NOT NULL,
                    ""ExpiresAt"" timestamp without time zone NOT NULL,
                    CONSTRAINT ""FK_TelegramVerifications_AspNetUsers_UserId""
                        FOREIGN KEY (""UserId"") REFERENCES ""AspNetUsers""(""Id"") ON DELETE CASCADE
                    );
                    CREATE INDEX ""IX_TelegramVerifications_UserId"" ON ""TelegramVerifications""(""UserId"");
                END IF;
                END$$;
            ");
        }


        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "TelegramVerifications");
        }
    }
}
